### ISSUE TITLE
Occasionally, orcmd does not respond to a killall orcmd (SIGTERM)

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#44]
Occasionally, orcmd does not respond to a killall orcmd (SIGTERM).

It does respond to a killall -9 (SIGKILL).

The backtrace is below.  However, we will need a gdb enabled build (--enable-debug on the config line) will be needed to get the symbols.

Details
<pre>
Missing separate debuginfos, use: debuginfo-install orcm-0.5+git+1410823125+4f92321-21.1.x86_64
(gdb) bt
#0  0x00007f5f288579c2 in fileno_unlocked () from /lib64/libc.so.6
#1  0x00007f5f296b3f73 in ?? () from /usr/lib64/libopen-pal.so.6
#2  0x00007f5f296b2655 in opal_output () from /usr/lib64/libopen-pal.so.6
#3  0x00007f5f27fda704 in ?? () from /usr/lib64/openmpi/mca_sst_orcmd.so
#4  0x00007f5f296c3802 in ?? () from /usr/lib64/libopen-pal.so.6
#5  0x00007f5f296c4324 in ?? () from /usr/lib64/libopen-pal.so.6
#6  0x00007f5f296c460e in ?? () from /usr/lib64/libopen-pal.so.6
#7  0x00007f5f296c4c8c in opal_libevent2021_event_base_loop () from /usr/lib64/libopen-pal.so.6
#8  0x00000000004022ce in main ()
</pre>

**Comment by noahv** [comment]
No longer seen in b7d61fe8478f1a845c4e0a288b716d272d30f110.  Closing.
